export const simulationAgentRuntimeDefinition = {
  id: 'simulation-agent',
  displayName: 'Virtual Learner Simulation Agent',
  description: '正式黑盒链路为 Virtual Learner -> Goal Conversation -> Path Result -> AI Teaching；Path Review 仅用于 legacy assisted 调试。',
  category: 'agent',
  steps: [
    { step: 1, agentId: 'skill:virtual-learner-goal-dialogue-simulator', role: 'goal-stage-learner-turn-simulation', loopOver: 'goal-rounds' },
    { step: 2, agentId: 'skill:goal-conversation', role: 'goal-clarification-and-convergence', loopOver: 'goal-rounds' },
    { step: 3, agentId: 'path-agent', role: 'learning-path-generation', condition: 'when goal stage converges' },
    { step: 4, agentId: 'skill:virtual-learner-path-evaluator', role: 'legacy-assisted-path-review', condition: 'legacy assisted mode only' },
    { step: 5, agentId: 'skill:virtual-learner-learn-turn-simulator', role: 'learn-stage-learner-turn-simulation', condition: 'when learning phase starts', loopOver: 'learning-turns' },
    { step: 6, agentId: 'learning-agent', role: 'learning-session-execution', condition: 'when learning phase starts', loopOver: 'learning-turns' },
    { step: 7, agentId: 'skill:virtual-learner-referee', role: 'platform-quality-referee', condition: 'after blackbox experiment reaches terminal state' },
    { step: 8, agentId: 'skill:virtual-learner-actor-auditor', role: 'synthetic-learner-fidelity-audit', condition: 'after blackbox experiment reaches terminal state' },
  ],
  variableGraph: {
    virtualLearnerSimulation: ['persona', 'story', 'learnerState', 'knowledgeState', 'reaction'],
    goalConversation: ['goalConversationId', 'goalStage', 'goalReady', 'collectedData'],
    pathGeneration: ['learningPathId', 'pathSummary', 'milestones'],
    legacyAssistedPathReview: ['review.decision', 'review.reasons', 'review.biggestConcern'],
    aiTeaching: ['teachingSessionId', 'learningProgress', 'teachingLogs'],
    platformRefereeEvaluation: ['verdict', 'scores', 'findings', 'recommendations', 'evidence'],
    actorFidelityAudit: ['verdict', 'scores', 'findings', 'recommendations', 'evidence'],
  },
  source: 'code',
  managedByCode: true,
};
