/**
 * Prompt 后处理器 - 对编译产物进行格式化和优化
 */

export interface PostProcessOptions {
  addMetadata?: boolean
  normalizeLineBreaks?: boolean
  removeExcessiveBlankLines?: boolean
  ensureSequentialNumbering?: boolean
}

/**
 * 后处理 Prompt
 */
export function postProcessPrompt(
  markdown: string,
  options: PostProcessOptions = {}
): string {
  let processed = markdown

  const {
    addMetadata = true,
    normalizeLineBreaks = true,
    removeExcessiveBlankLines = true,
    ensureSequentialNumbering = true
  } = options

  // 1. 统一换行符
  if (normalizeLineBreaks) {
    processed = normalizeLineBreaksImpl(processed)
  }

  // 2. 移除多余空行
  if (removeExcessiveBlankLines) {
    processed = removeExcessiveBlankLinesImpl(processed)
  }

  // 3. 确保编号连续
  if (ensureSequentialNumbering) {
    processed = ensureSequentialNumberingImpl(processed)
  }

  // 4. 添加元数据注释
  if (addMetadata) {
    processed = addMetadataCommentsImpl(processed)
  }

  return processed
}

/**
 * 统一换行符（CRLF → LF）
 */
function normalizeLineBreaksImpl(text: string): string {
  return text.replace(/\r\n/g, '\n')
}

/**
 * 移除多余空行（连续 3+ 个空行 → 2 个）
 */
function removeExcessiveBlankLinesImpl(text: string): string {
  // 连续 3 个或以上的空行替换为 2 个
  return text.replace(/\n{3,}/g, '\n\n')
}

/**
 * 确保编号连续
 */
function ensureSequentialNumberingImpl(text: string): string {
  let processed = text

  // 重新编号 RULE-XX
  processed = renumberSection(processed, 'RULE')

  // 重新编号 OUT-XX
  processed = renumberSection(processed, 'OUT')

  // 重新编号 CON-XX
  processed = renumberSection(processed, 'CON')

  return processed
}

/**
 * 重新编号某个类型的规则
 */
function renumberSection(text: string, prefix: string): string {
  let counter = 1
  const regex = new RegExp(`${prefix}-\\d{2}`, 'g')

  return text.replace(regex, () => {
    const newNumber = String(counter++).padStart(2, '0')
    return `${prefix}-${newNumber}`
  })
}

/**
 * 添加元数据注释
 */
function addMetadataCommentsImpl(text: string): string {
  const metadata = [
    `<!-- Generated by Blueprint Compiler -->`,
    `<!-- Compiled at: ${new Date().toISOString()} -->`,
    `<!-- Compiler version: 3.0.0 -->`,
    ''
  ].join('\n')

  // 在 frontmatter 之后插入
  const frontmatterEnd = text.indexOf('---', 3)
  if (frontmatterEnd !== -1) {
    const before = text.substring(0, frontmatterEnd + 3)
    const after = text.substring(frontmatterEnd + 3)
    return before + '\n\n' + metadata + after
  }

  // 如果没有 frontmatter，插入到开头
  return metadata + '\n' + text
}

/**
 * 格式化代码块
 */
export function formatCodeBlocks(text: string): string {
  // 确保代码块前后有空行
  let formatted = text.replace(/([^\n])\n```/g, '$1\n\n```')
  formatted = formatted.replace(/```\n([^\n])/g, '```\n\n$1')
  return formatted
}

/**
 * 验证编译产物
 */
export interface ValidationResult {
  valid: boolean
  issues: string[]
}

export function validateCompiledPrompt(markdown: string): ValidationResult {
  const issues: string[] = []

  // 1. 检查是否有 frontmatter
  if (!markdown.startsWith('---')) {
    issues.push('缺少 frontmatter')
  }

  // 2. 检查必要的章节
  const requiredSections = ['## 身份定义', '## 输出规格']
  requiredSections.forEach(section => {
    if (!markdown.includes(section)) {
      issues.push(`缺少必要章节: ${section}`)
    }
  })

  // 3. 检查编号是否连续
  const ruleNumbers = extractNumbers(markdown, 'RULE')
  if (!isSequential(ruleNumbers)) {
    issues.push('RULE 编号不连续')
  }

  const outNumbers = extractNumbers(markdown, 'OUT')
  if (!isSequential(outNumbers)) {
    issues.push('OUT 编号不连续')
  }

  // 4. 检查是否有过多空行
  if (/\n{4,}/.test(markdown)) {
    issues.push('存在过多空行（连续 4 个以上）')
  }

  return {
    valid: issues.length === 0,
    issues
  }
}

/**
 * 提取编号
 */
function extractNumbers(text: string, prefix: string): number[] {
  const regex = new RegExp(`${prefix}-(\\d{2})`, 'g')
  const numbers: number[] = []
  let match

  while ((match = regex.exec(text)) !== null) {
    numbers.push(parseInt(match[1], 10))
  }

  return numbers
}

/**
 * 检查编号是否连续
 */
function isSequential(numbers: number[]): boolean {
  if (numbers.length === 0) return true

  for (let i = 0; i < numbers.length; i++) {
    if (numbers[i] !== i + 1) {
      return false
    }
  }

  return true
}

/**
 * 生成编译报告
 */
export interface CompilationReport {
  linesCount: number
  charactersCount: number
  rulesCount: number
  outputRulesCount: number
  constraintsCount: number
  sectionsCount: number
}

export function generateCompilationReport(markdown: string): CompilationReport {
  const lines = markdown.split('\n')
  const ruleMatches = markdown.match(/RULE-\d{2}/g) || []
  const outMatches = markdown.match(/OUT-\d{2}/g) || []
  const conMatches = markdown.match(/CON-\d{2}/g) || []
  const sectionMatches = markdown.match(/^##\s+/gm) || []

  return {
    linesCount: lines.length,
    charactersCount: markdown.length,
    rulesCount: ruleMatches.length,
    outputRulesCount: outMatches.length,
    constraintsCount: conMatches.length,
    sectionsCount: sectionMatches.length
  }
}
