import { RuntimeDefinitionRecord } from '../../composers/definitions/types';

export const teachingTurnRuntimeDefinition: RuntimeDefinitionRecord = {
  id: 'skill:teaching-turn',
  displayName: '教学回合',
  description: '根据任务、路径、学习者状态和当前对话，生成单轮教学回复与结构化教学状态。',
  category: 'skill',
  inputSchema: {
    type: 'object',
    properties: {
      messages: { type: 'array' },
      scenario: { type: 'object' },
      learner: { type: 'object' },
      knowledge: { type: 'object' },
      controls: { type: 'object' },
    },
    required: ['messages', 'scenario', 'knowledge'],
  },
  outputSchema: {
    type: 'object',
    properties: {
      reply: { type: 'string' },
      analysis: { type: 'object' },
      knowledge: { type: 'object' },
      pedagogy: { type: 'object' },
      control: { type: 'object' },
    },
    required: ['reply', 'analysis', 'knowledge', 'pedagogy', 'control'],
  },
  variableBindings: {
    consumes: [
      'messages[]',
      'scenario.taskTitle',
      'scenario.taskDescription',
      'scenario.taskType',
      'scenario.taskProfile.knowledgeType',
      'scenario.taskProfile.cognitiveLevel',
      'scenario.taskProfile.linkedConceptName',
      'scenario.cognitiveFrame.currentCoreConcept',
      'scenario.cognitiveFrame.targetRelation',
      'scenario.cognitiveFrame.prerequisiteConcepts',
      'scenario.taskKnowledgeScope.primaryConcepts',
      'scenario.taskKnowledgeScope.supportingConcepts',
      'scenario.currentTaskContext.description',
      'scenario.currentTaskContext.acceptanceCriteria',
      'scenario.teachingStrategyGuidance',
      'scenario.currentMilestoneTitle',
      'scenario.currentStageNumber',
      'knowledge.points[]',
      'controls.mode',
    ],
    produces: [
      'reply',
      'analysis.cognitiveLevel',
      'analysis.understanding',
      'analysis.confusionPoints',
      'analysis.engagement',
      'knowledge.currentPoint',
      'knowledge.points[]',
      'pedagogy.strategies[]',
      'control.isCompletionCandidate',
      'control.shouldTriggerPeer',
    ],
  },
  capabilities: [
    'teaching-turn-generation',
    'cognitive-analysis',
    'knowledge-state-suggestion',
    'teaching-strategy-selection',
  ],
  defaultMaxTokens: 4000,
  defaultTemperature: 0.7,
  source: 'code',
  managedByCode: true,
};
